theme: minima
title: Vision-Language Action Models: Real-World Evaluation
description: Weekly updates on our MSc dissertation exploring Vision-Language Action (VLA) models, with a focus on real-world benchmarking using the SO-101 robotic arm.
author: justintiensmith & mattpidden
